// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCxTS0cJG1Y6GpkIp7ijnj3qVppiBV0ck',
    appId: '1:135583262145:web:d930d559a6b46a83f6fb40',
    messagingSenderId: '135583262145',
    projectId: 'kimo-3f95e',
    authDomain: 'kimo-3f95e.firebaseapp.com',
    storageBucket: 'kimo-3f95e.appspot.com',
    measurementId: 'G-DJ79ZZB6P3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiaMWMG9l3zFQulxIjzyaIB2pP-1SuSao',
    appId: '1:135583262145:android:83a1dcd08f2d443af6fb40',
    messagingSenderId: '135583262145',
    projectId: 'kimo-3f95e',
    storageBucket: 'kimo-3f95e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDteqXgI5I_C4H0minZjucOD_bfyE1MPPc',
    appId: '1:135583262145:ios:766a95564111bdddf6fb40',
    messagingSenderId: '135583262145',
    projectId: 'kimo-3f95e',
    storageBucket: 'kimo-3f95e.appspot.com',
    iosBundleId: 'com.example.kimo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDteqXgI5I_C4H0minZjucOD_bfyE1MPPc',
    appId: '1:135583262145:ios:766a95564111bdddf6fb40',
    messagingSenderId: '135583262145',
    projectId: 'kimo-3f95e',
    storageBucket: 'kimo-3f95e.appspot.com',
    iosBundleId: 'com.example.kimo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCxTS0cJG1Y6GpkIp7ijnj3qVppiBV0ck',
    appId: '1:135583262145:web:b325d5481e5bb69df6fb40',
    messagingSenderId: '135583262145',
    projectId: 'kimo-3f95e',
    authDomain: 'kimo-3f95e.firebaseapp.com',
    storageBucket: 'kimo-3f95e.appspot.com',
    measurementId: 'G-QVSVFBE5QW',
  );

}